<a href="https://colab.research.google.com/github/maefl0wer/Statistics2022/blob/main/bloom_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#loops

In [5]:
for i in range (10):
  print(i)
#print number in range of 0-10

0
1
2
3
4
5
6
7
8
9


In [6]:
for i in range(5,8):
  print (i)
#prints numbers in the range of 5-8, not including 8

5
6
7


In [7]:
for i in range (3):
  print("test number:" , i)
#including a string and adding text

test number: 0
test number: 1
test number: 2


#functions

In [8]:
def square(x):
  return x**2
#given a variable, will print the square of that value

In [9]:
square(5)

25

In [10]:
square(3)

9

In [11]:
square(1245)

1550025

In [12]:
square(square(5))

625

In [13]:
def add_two(x):
  return x+2

In [14]:
add_two(5)
#adds 2 to 5

7

In [15]:
square(add_two(5))
#makes the 5 a 7

49

In [16]:
square(7)

49

#logical branching

In [17]:
choice = "apple"

In [18]:
if choice == "apple":
  print("you choose apples.")

else:
  print("you did not choose apples")

you choose apples.


In [19]:
choice = "orange"

In [20]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [21]:
if choice == "apple":
  print("you choose apples.")

elif choice == "orange":
  print("you choose oranges.")

else:
  print("you did not choose apples or oranges")

#whats tabbed in each shows what happens when each choice is made

you choose oranges.


#user input

In [22]:
#choice = input("please enter your choice (i.e. apple):")
#how to get input from the user

In [23]:
choice

'orange'

In [24]:
if choice == "apple":

    print("you choose apples.")

elif choice == "oranges":

    print("you choose oranges.")

else:
    
    print("you did not choose apples or oranges.")

you did not choose apples or oranges.


#speed test

In [25]:
import numpy as np

In [26]:
from IPython.core.display import display, HTML

In [27]:
np.random.permutation(52)
#giving the number in parenthesis in a random order (shuffling basically)

array([20, 47, 22, 25,  1, 42,  8, 23, 18, 28, 24,  6, 27, 33, 37, 15, 40,
       29, 17, 30, 36,  2, 39, 12, 14, 26, 44,  9, 19, 48,  3,  0, 10, 45,
       16,  5, 49,  7, 51,  4, 35, 11, 32, 43, 41, 31, 34, 50, 46, 38, 21,
       13])

In [28]:
cards = np.random.permutation(52)
#defining cards as the array of 52 numbers

In [29]:
cards 

array([33, 20, 12, 50, 34, 28,  3, 15, 42, 41, 19, 31, 26, 37, 23, 43, 22,
       46, 18, 11, 13, 47, 45,  4, 27,  9,  2, 39, 14, 48, 24, 29, 21, 36,
        1, 44, 40, 51, 38,  6, 25, 35,  7, 30,  5, 49, 16, 32,  0,  8, 10,
       17])

In [30]:
cards[0]
#gives you the first card in the list

33

In [31]:
cards[5]
#gives you the 6th card in the list

28

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [32]:
np.arange(52).reshape(4,13)
#reshaping as four rows and 13 collumns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [33]:
np.arange(52).reshape(4,13)%13
#dividing out as many whole 13's as it can

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [34]:
np.arange(52).reshape(4,13)//13
#floor division

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [35]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']
#defining suits and names

In [36]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [37]:
names

['Ace',
 'Two',
 'Three',
 'Four',
 'Five',
 'Six',
 'Seven',
 'Eight',
 'Nine',
 'Ten',
 'Jack',
 'Queen',
 'King']

In [38]:
suits[0]

'Clubs'

In [39]:
names[1]

'Two'

In [40]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

#defining the cards and showing computer how to name them

In [41]:
card_name(4)

'Five of Clubs'

In [42]:
card_name(51)

'King of Diamonds'

In [43]:
card_name(17)

'Five of Spades'

In [44]:
card_name(45)

'Seven of Diamonds'

In [45]:
cards = np.random.permutation(52)

In [46]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

#-1 means the last card from the end

In [47]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Diamonds', 'Ace of Hearts', 'King of Diamonds')

In [48]:
for i in range(5):
  print(card_name(cards[i]))

#printing 5 random cards

Three of Diamonds
Ace of Hearts
Jack of Hearts
Four of Spades
Seven of Spades


In [49]:
for i in range(15):
  print(card_name(cards[i]))


Three of Diamonds
Ace of Hearts
Jack of Hearts
Four of Spades
Seven of Spades
Six of Hearts
Three of Spades
Seven of Diamonds
Four of Clubs
Three of Hearts
Ace of Clubs
King of Clubs
Four of Hearts
King of Spades
Eight of Clubs


In [50]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [51]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [52]:
i = np.random.randint(4)
j = np.random.randint(13)
#defining i & j

In [53]:
i, j

(3, 9)

In [54]:
suit[i]

'l'

In [55]:
card[j]

'10'

In [56]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))
#following scripts are for creating an image graphic

In [57]:
img = card_url_head + suit[i]+card[j] + card_url_tail
#telling the computer that the action of img should show the card head of i and card tail of j

In [58]:
show_img(img)

In [59]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [60]:
img = card_url_head + card_image(3) + card_url_tail

In [64]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)